services:
  - type: web
    name: zmm-backend
    env: node
    buildCommand: npm install && cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 4000
